/**
 * project-atlas · a system prompt assembled from what is true
 *
 * `AGENTS.md` and every `SKILL.md` are hand-written, and they drift from the repository they describe. That
 * is the failure this tool detects everywhere else, occurring in the one document whose whole job is to tell
 * an assistant how to work here — and nothing checks it, because prose about conventions has no citation to
 * resolve and no link to break.
 *
 * So this does not *describe* the conventions. It reads them:
 *
 *   - the taxonomy, from the configured clusters
 *   - the blocking signals, from `blocking`
 *   - the branch convention and protected branches, from `branch.mjs` and the config
 *   - what counts as shipped, from `release.mjs`'s runtime globs
 *   - the plan's shape, from the planning document
 *   - the corpus's current health, from the health run
 *
 * Change a cluster rule and the prompt changes. That is the entire point: a generated prompt cannot claim a
 * convention the repository does not have.
 *
 * ## What it deliberately does not do
 *
 * It does not write judgement. There is no "be helpful", no tone, no worked examples — those are a person's
 * to write, and a generated file that contained them would be unreviewed generated prose, which this project
 * refuses everywhere else. What it emits is the machine-checkable half: the rules, and the current state.
 *
 * It is opt-in and written where the caller says. Nothing is overwritten by a build.
 */

import { TYPES } from './branch.mjs';
import { RUNTIME_GLOBS } from './release.mjs';
import { SIGNALS } from './signals.mjs';

const bullet = (s) => `- ${s}`;

/**
 * @param {object} a
 * @param {object} a.cfg      resolved configuration
 * @param {object} a.index    the corpus index
 * @param {object} a.health   the health run
 * @param {object|null} a.plan the planning document, when one is configured
 * @param {string} a.version  the plugin version, so the prompt states which build described this
 * @param {string} a.slug     owner/repo, or the directory name when there is no remote
 */
export function buildPrompt({ cfg, index, health, plan, version, slug }) {
  const L = [];
  const blocking = (cfg.blocking || []).filter((id) => SIGNALS[id]);
  const advisory = Object.keys(SIGNALS).filter((id) => !blocking.includes(id));

  L.push(`# Working in ${slug}`);
  L.push('');
  L.push(`<!-- GENERATED by \`atlas prompt\` from project-atlas ${version}. Do not edit: every statement below`);
  L.push(`     is read from this repository's configuration, plan and corpus, so editing here changes nothing`);
  L.push('     and will be overwritten. Change the rule, then regenerate. -->');
  L.push('');
  L.push('## The rule everything else follows');
  L.push('');
  L.push('**The markdown is the source of truth. Everything generated is derived and safe to delete.**');
  L.push('If a figure looks wrong on a generated page, the fix is in the markdown — never in the output.');
  L.push('');

  /* ---------------------------------------------------------------- corpus */
  L.push('## What is here');
  L.push('');
  L.push(`- ${index.documents.length} document(s), ${index.stats?.lines ?? '?'} line(s), in ${index.clusters?.length ?? 0} cluster(s).`);
  if (plan && !plan.missing) {
    L.push(`- A plan at \`${plan.source}\`: ${plan.items.length} item(s) across ${plan.tracks.length} track(s), mean completion ${plan.stats.mean ?? '—'}%.`);
  } else {
    L.push('- No planning document is configured, so there is no item list to advance.');
  }
  L.push('');

  /* ------------------------------------------------------------- taxonomy */
  L.push('## Where a document belongs');
  L.push('');
  L.push('Clusters are matched in order; the first rule that matches wins. A document matching none falls to');
  L.push(`\`${cfg.fallbackCluster || 'uncategorised'}\`, which is itself a finding (${SIGNALS.H5.id}).`);
  L.push('');
  for (const c of cfg.clusters || []) {
    L.push(bullet(`**${c.title}** — ${(c.match || []).map((m) => `\`${m}\``).join(', ') || 'no rule'}`));
  }
  L.push('');

  /* -------------------------------------------------------------- signals */
  L.push('## What will refuse your commit');
  L.push('');
  if (blocking.length) {
    L.push('These are **blocking**. They have no legitimate cause, so a commit that introduces one is refused:');
    L.push('');
    for (const id of blocking) L.push(bullet(`**${id} · ${SIGNALS[id].title}** — ${SIGNALS[id].why}`));
  } else {
    L.push('No signal is configured as blocking, so nothing here refuses a commit.');
  }
  L.push('');
  L.push('The rest are **advisory**: they have legitimate causes, and are reported rather than enforced —');
  L.push(`${advisory.join(', ')}.`);
  L.push('');
  L.push(`Currently: **${health.findings.filter((f) => f.blocking).length} blocking**, ` +
         `${health.findings.filter((f) => !f.suppressed && !f.blocking).length} advisory, ` +
         `${health.findings.filter((f) => f.suppressed).length} suppressed with a stated reason.`);
  L.push('');

  /* --------------------------------------------------------------- branch */
  L.push('## How a change gets in');
  L.push('');
  const protectedList = ['main', 'master', 'develop', ...(cfg.branching?.protected || [])];
  L.push(`Protected: ${[...new Set(protectedList)].map((b) => `\`${b}\``).join(', ')}. Work on a branch named`);
  L.push('`type/short-slug`, where type is one of:');
  L.push('');
  for (const [t, why] of Object.entries(TYPES)) L.push(bullet(`\`${t}\` — ${why}`));
  L.push('');
  L.push('A shipped change must name the plan item it advances in the commit subject, and must move the');
  L.push('version. **Shipped** means a path an installed plugin executes or reads:');
  L.push('');
  L.push(RUNTIME_GLOBS.map((g) => `\`${g}\``).join(', ') + '.');
  L.push('');

  /* --------------------------------------------------------------- honesty */
  L.push('## Honesty rules, which the output enforces');
  L.push('');
  L.push(bullet('A figure that was **estimated** says so beside the figure.'));
  L.push(bullet('A check that **did not run** is listed under *Not checked* — never omitted, never reported as clean.'));
  L.push(bullet('A **suppressed** finding carries a stated reason.'));
  L.push(bullet('A **capped** analysis reports its cap: a sample presented as a total is a lie.'));
  L.push(bullet('Nothing is published without an explicit `--push`, every time.'));
  L.push('');

  /* ------------------------------------------------------------------ plan */
  if (plan && !plan.missing && plan.items.length) {
    const open = plan.items.filter((i) => (i.percent ?? 0) < 100)
      .sort((a, b) => (a.priority || '').localeCompare(b.priority || ''));
    L.push('## What is open');
    L.push('');
    if (!open.length) {
      L.push('Every item in the plan is at 100%.');
    } else {
      L.push(`${open.length} of ${plan.items.length} item(s) are not complete. The highest-priority ones:`);
      L.push('');
      for (const i of open.slice(0, 12)) {
        L.push(bullet(`**${i.id}** ${i.title} — ${i.priority}, ${i.percent === null ? 'no figure' : i.percent + '%'}`));
      }
    }
    L.push('');
  }

  L.push('---');
  L.push('');
  L.push('_Generated. Every statement above was read from this repository — the configuration, the plan, the');
  L.push('corpus and its health. It contains no judgement about how to work, deliberately: that is a person\'s');
  L.push('to write, and generated prose nobody reviewed is what this project exists to detect._');
  L.push('');
  return L.join('\n');
}
